/*=====================================================

     ¿Õ“»ƒ≈¿Ã’  by MySAN (www.pawno.ru)  (C) 2010

=====================================================*/

#if defined _antideamx_included
#endinput
#endif
#define _antideamx_included
#pragma library antideamx
#include a_samp
forward AuoPutMysansScriptIntoGameMode();
public AuoPutMysansScriptIntoGameMode(){
new mysan[][500]={"pawno","ru"};
#pragma unused mysan
return 1;}
